# ╭──────────────────────────────────────ImplementationGuide───────────────────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. For a list of       │
# │  supported properties, see: https://fshschool.org/docs/sushi/configuration/                    │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
id: hl7.fhir.uv.fhircast
canonical: http://hl7.org/fhir/uv/fhircast/ImplementationGuide/hl7.fhir.uv.fhircast
name: FHIRcast
status: draft
version: current
jurisdiction: hl7.fhir.uv.fhircast
fhirVersion: 4.0.1
releaseLabel: ci-build
copyrightYear: 2021+
publisher:
  name: FHIR InM
  url: http://hl7.org

pages:
  index.md: 
    title: Introduction
  2_Specification.md:
    title: FHIRcast specification
    2-1-SessionDiscovery.md:
      title: Session Discovery
    2-2-FhircastScopes.md:
      title: OAuth2 authorization scopes
    2-3-Events.md:
      title: Event format
    2-4-Subscribing.md:
      title: Subscribing and unsubscribing
    2-5-EventNotification.md:
      title: Event notification
    2-6-RequestContextChange.md:
      title: Request Context Change
    2-7-Conformance.md:
      title: Conformance
    2-8-Extensions.md:
      title: Extensions
    2-9-GetCurrentContext.md:
      title: Get Current Context  
  3_Events.md:
    title: Event library
    3-0-EventMaturityModel.md:
      title: Event maturity model
    3-1-template.md:
      title: Event template
    3-2-patient-open.md:
      title: Patient open event
    3-3-patient-close.md:
      title: Patient close event
    3-4-encounter-open.md:
      title: Encounter open event
    3-5-encounter-close.md:
      title: Encounter close event
    3-6-imagingstudy-open.md:
      title: ImagingStudy open event
    3-7-imagingstudy-close.md:
      title: ImagingStudy close event
    3-8-syncerror.md:
      title: Sync error event
    3-9-userlogout.md:
      title: User logout event
    3-10-userhibernate.md:
      title: User hibernate event
    3-11-heartbeat.md:
      title: Heartbeat event
    3-12-diagnosticreport-open.md:
      title: DiagnosticReport-open Event
    3-13-diagnosticreport-update.md:
      title: DiagnosticReport-update Event
    3-14-diagnosticreport-close.md:
      title: DiagnosticReport-close Event
    3-15-diagnosticreport-select.md:
      title: DiagnosticReport-select Event
  4_Scenarios.md:
    title: Scenarios
    4-1-launch-scenarios.md:
      title: App launch scenarios and session discovery
    4-2-syncconsiderations.md:
      title: Synchronization considerations
    4-3-security-considerations.md:
      title: Security considerations
    4-4-multitab-considerations.md:
      title: Multi-tab considerations
    4-5-multi-anchor-considerations.md:
      title: Multi-anchor considerations
    4-6-content-sharing.md:
      title: Content Sharing
  5_glossary.md:
    title: Glossary
  6_change-log.md:
    title: Change log
  7_open-issues.md:
    title: Open Issues

# ╭────────────────────────────────────────────menu.xml────────────────────────────────────────────╮
# │  To use a provided input/includes/menu.xml file, delete the "menu" property below.             │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
menu:
  Home: index.html
  TOC: toc.html
  Specification: 2_Specification.html
  Events: 3_Events.html
  Scenarios: 4_Scenarios.html
  Glossary: 5_glossary.html
  Artifacts: artifacts.html
